import Link from "next/link";
import { notFound } from "next/navigation";
import { createAdminClient } from "@/lib/supabase/server";
import ItemsTable from "@/components/ItemsTable";
import KpiBar from "@/components/KpiBar";
import CollectionHero from "@/components/CollectionHero";
import DonateButton from "@/components/DonateButton";
import CollectionValueChart from "@/components/CollectionValueChart";
import { loadCollectionHistory } from "@/lib/history";
import { loadItemTrends } from "@/lib/trends";
import type { MangaItem } from "@/lib/types";

/**
 * Public read-only view of a user's collection, reachable via the link
 * generated by the "Condividi" button on the dashboard. Resolves the slug
 * to a user_id server-side with the admin (service role) client - the same
 * pattern already used by /api/mcp and /api/collection - so no RLS changes
 * or anon-facing policies are needed. Never renders any mutation controls.
 */
export default async function SharedCollectionPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const admin = createAdminClient();

  const { data: profile } = await admin
    .from("profiles")
    .select("id, display_name, share_enabled")
    .eq("share_slug", slug)
    .maybeSingle();

  if (!profile || !profile.share_enabled) notFound();

  const [{ data: items }, history, trends] = await Promise.all([
    admin.from("items").select("*").eq("user_id", profile.id).order("created_at", { ascending: false }),
    loadCollectionHistory(admin, profile.id),
    loadItemTrends(admin, profile.id),
  ]);

  return (
    <main className="min-h-screen bg-slate-950 px-4 py-8 text-slate-50 sm:px-8">
      <CollectionHero
        eyebrow="私のコレクション · Sola lettura"
        title={`La collezione di ${profile.display_name || "un collezionista"},`}
        highlight="volume dopo volume."
        description="Una raccolta condivisa pubblicamente: sfogliala, ma solo il proprietario può modificarla."
        footer={
          <Link href="/dashboard" className="underline transition hover:text-slate-300">
            Gestisci la tua collezione su Manga Collection
          </Link>
        }
        actions={<DonateButton />}
      />

      <KpiBar items={(items ?? []) as MangaItem[]} />

      <CollectionValueChart points={history} />

      <ItemsTable items={(items ?? []) as MangaItem[]} trends={trends} readOnly />
    </main>
  );
}
