import Link from "next/link";
import { notFound } from "next/navigation";
import { createAdminClient } from "@/lib/supabase/server";
import ItemsTable from "@/components/ItemsTable";
import KpiBar from "@/components/KpiBar";
import type { MangaItem } from "@/lib/types";

/**
 * Public read-only view of a user's collection, reachable via the link
 * generated by the "Condividi" button on the dashboard. Resolves the slug
 * to a user_id server-side with the admin (service role) client - the same
 * pattern already used by /api/mcp and /api/collection - so no RLS changes
 * or anon-facing policies are needed. Never renders any mutation controls.
 */
export default async function SharedCollectionPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const admin = createAdminClient();

  const { data: profile } = await admin
    .from("profiles")
    .select("id, display_name, share_enabled")
    .eq("share_slug", slug)
    .maybeSingle();

  if (!profile || !profile.share_enabled) notFound();

  const { data: items } = await admin
    .from("items")
    .select("*")
    .eq("user_id", profile.id)
    .order("created_at", { ascending: false });

  return (
    <main className="min-h-screen bg-slate-950 px-4 py-8 text-slate-50 sm:px-8">
      <header className="mb-6 flex flex-wrap items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold">
            📚 Collezione di {profile.display_name || "un collezionista"}
          </h1>
          <p className="text-sm text-slate-400">
            👁️ Sola lettura — condivisa pubblicamente,{" "}
            <Link href="/dashboard" className="underline hover:text-slate-300">
              gestisci la tua su Manga Collection
            </Link>
          </p>
        </div>
      </header>

      <KpiBar items={(items ?? []) as MangaItem[]} />

      <ItemsTable items={(items ?? []) as MangaItem[]} readOnly />
    </main>
  );
}
